# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ChooseSomeone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChooseSomeone

  pod 'SwiftLint'
  pod 'IQKeyboardManagerSwift'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseFirestore'
  pod 'Firebase/Core'
  pod 'FirebaseStorage'
  pod 'FirebaseStorageSwift'
  pod 'MJRefresh'
  pod 'MASegmentedControl'
  pod 'Kingfisher'

end
